services:
  free-games-notifier:
    build: .
    container_name: free-games-notifier
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL} 
      - HEALTHCHECK_URL=${HEALTHCHECK_URL}
      - ENABLE_HEALTHCHECK=${ENABLE_HEALTHCHECK}
      - EPIC_GAMES_API_URL=${EPIC_GAMES_API_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    image: free-games-notifier
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${DATA_PATH}
        target: /mnt/data
      - type: bind
        source: ${LOGS_PATH}
        target: /mnt/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - apollo-server-network

networks:
  apollo-server-network:
    external: true